import { Download, Loader2, Trash2 } from 'lucide-react';

import { cn } from '@/lib/utils';
import type { GeneratedReport } from '../types';
import { STATUS_META, fmtSize, relativeTime } from '../helpers';

interface GeneratedRowProps {
  report: GeneratedReport;
  /** Re-fetch the data and re-render the PDF (we don't store the binary). */
  onDownload?: () => void;
  onDelete?: () => void;
  /** True while this row's PDF is being (re)generated. */
  busy?: boolean;
}

export function GeneratedRow({ report, onDownload, onDelete, busy }: GeneratedRowProps) {
  const meta = STATUS_META[report.status];
  const isReady = report.status === 'ready';

  return (
    <li className="grid grid-cols-[1.6fr_1fr_120px_180px_120px] items-center gap-3 border-b border-foreground/[0.04] px-5 py-3 last:border-0">
      {/* Name + target */}
      <div className="min-w-0">
        <div className="truncate text-sm font-medium text-foreground">{report.templateName}</div>
        <div className="truncate text-[11px] text-foreground/75 dark:text-foreground/60">
          {report.target ? <span>{report.target} · </span> : null}
          {report.period}
        </div>
      </div>

      {/* Generated by */}
      <div className="truncate text-xs text-foreground/80 dark:text-foreground/65">{report.generatedBy}</div>

      {/* Size */}
      <div className="text-xs text-foreground/75 dark:text-foreground/55">
        {isReady ? (
          <span>
            {report.pageCount ? `${report.pageCount}p · ` : ''}{fmtSize(report.sizeKb)}
          </span>
        ) : (
          <span className="text-foreground/35">—</span>
        )}
      </div>

      {/* Status */}
      <div>
        <span className={cn('inline-flex items-center gap-1.5 rounded-full border px-2.5 py-0.5 text-[10px] uppercase tracking-[0.16em]', meta.chip)}>
          {report.status === 'generating' ? (
            <Loader2 className="h-3 w-3 animate-spin" />
          ) : (
            <span className={cn('h-1.5 w-1.5 rounded-full', meta.dot)} />
          )}
          {meta.label}
        </span>
        <div className="mt-1 text-[10px] text-foreground/75 dark:text-foreground/55">{relativeTime(report.generatedAt)}</div>
      </div>

      {/* Actions */}
      <div className="flex items-center justify-end gap-1">
        {isReady && onDownload && (
          <button
            type="button"
            onClick={onDownload}
            disabled={busy}
            className="grid h-8 w-8 place-items-center rounded-lg text-foreground/75 dark:text-foreground/55 hover:bg-foreground/[0.05] hover:text-foreground disabled:opacity-50"
            aria-label="Download"
            title="Re-generate &amp; download"
          >
            {busy ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <Download className="h-3.5 w-3.5" />}
          </button>
        )}
        {onDelete && (
          <button
            type="button"
            onClick={onDelete}
            className="grid h-8 w-8 place-items-center rounded-lg text-foreground/75 dark:text-foreground/60 hover:bg-foreground/[0.05] hover:text-rose-600 dark:hover:text-rose-300"
            aria-label="Delete"
            title="Delete from history"
          >
            <Trash2 className="h-3.5 w-3.5" />
          </button>
        )}
      </div>
    </li>
  );
}
