import { Download, Eye, MoreHorizontal, Loader2, Mail } from 'lucide-react';
import { toast } from 'sonner';

import { cn } from '@/lib/utils';
import type { GeneratedReport } from '../types';
import { STATUS_META, fmtSize, relativeTime } from '../helpers';

interface GeneratedRowProps {
  report: GeneratedReport;
}

export function GeneratedRow({ report }: GeneratedRowProps) {
  const meta = STATUS_META[report.status];
  const isReady = report.status === 'ready';

  return (
    <li className="grid grid-cols-[1.6fr_1fr_120px_180px_120px] items-center gap-3 border-b border-white/[0.04] px-5 py-3 last:border-0">
      {/* Name + target */}
      <div className="min-w-0">
        <div className="truncate text-sm font-medium text-white">{report.templateName}</div>
        <div className="truncate text-[11px] text-white/45">
          {report.target ? <span>{report.target} · </span> : null}
          {report.period}
        </div>
      </div>

      {/* Generated by */}
      <div className="text-xs text-white/65">{report.generatedBy}</div>

      {/* Size */}
      <div className="text-xs text-white/55">
        {isReady ? (
          <span>
            {report.pageCount}p · {fmtSize(report.sizeKb)}
          </span>
        ) : (
          <span className="text-white/35">—</span>
        )}
      </div>

      {/* Status */}
      <div>
        <span className={cn('inline-flex items-center gap-1.5 rounded-full border px-2.5 py-0.5 text-[10px] uppercase tracking-[0.16em]', meta.chip)}>
          {report.status === 'generating' ? (
            <Loader2 className="h-3 w-3 animate-spin" />
          ) : (
            <span className={cn('h-1.5 w-1.5 rounded-full', meta.dot)} />
          )}
          {meta.label}
        </span>
        <div className="mt-1 text-[10px] text-white/40">{relativeTime(report.generatedAt)}</div>
      </div>

      {/* Actions */}
      <div className="flex items-center justify-end gap-1">
        {isReady && (
          <>
            <button
              type="button"
              onClick={() => toast.success(`Opening ${report.templateName}.pdf`)}
              className="grid h-8 w-8 place-items-center rounded-lg text-white/55 hover:bg-white/[0.05] hover:text-white"
              aria-label="View"
            >
              <Eye className="h-3.5 w-3.5" />
            </button>
            <button
              type="button"
              onClick={() => toast.success(`Downloading ${report.templateName}.pdf`)}
              className="grid h-8 w-8 place-items-center rounded-lg text-white/55 hover:bg-white/[0.05] hover:text-white"
              aria-label="Download"
            >
              <Download className="h-3.5 w-3.5" />
            </button>
            <button
              type="button"
              onClick={() => toast.success('Send dialog opens when the Settings module ships email.')}
              className="grid h-8 w-8 place-items-center rounded-lg text-white/55 hover:bg-white/[0.05] hover:text-white"
              aria-label="Email"
            >
              <Mail className="h-3.5 w-3.5" />
            </button>
          </>
        )}
        <button
          type="button"
          onClick={() => toast(`More actions for ${report.templateName}`)}
          className="grid h-8 w-8 place-items-center rounded-lg text-white/45 hover:bg-white/[0.05] hover:text-white"
          aria-label="More"
        >
          <MoreHorizontal className="h-3.5 w-3.5" />
        </button>
      </div>
    </li>
  );
}
