/**
 * Curated wellness / nutrition / dietician motivational quotes (~500).
 *
 * One is shown per day — the SAME quote for everyone that calendar day — on the
 * client Home banner (as the default when the client hasn't set their own) and
 * on the nutritionist dashboard. Rotation is deterministic by day via
 * `quoteOfTheDay()`, so both portals stay in sync and cycle through the whole
 * set over time.
 */
export const WELLNESS_QUOTES: string[] = [
  // ── Food & nutrition wisdom ──
  'Let food be thy medicine and medicine be thy food. — Hippocrates',
  'The food you eat can be either the safest form of medicine or the slowest form of poison. — Ann Wigmore',
  'Eat to nourish your body, not just to fill it.',
  'You are what you eat, so don’t be fast, cheap, easy, or fake.',
  'Real food doesn’t have ingredients — real food is ingredients.',
  'Nourishing yourself in a way that helps you blossom is an act of love.',
  'Eat food. Not too much. Mostly plants. — Michael Pollan',
  'The first wealth is health. — Ralph Waldo Emerson',
  'The greatest wealth is health. — Virgil',
  'Your diet is a bank account — good food choices are good investments.',
  'A healthy outside starts from the inside. — Robert Urich',
  'To eat is a necessity, but to eat intelligently is an art. — François de La Rochefoucauld',
  'He who has health has hope, and he who has hope has everything. — Arabian Proverb',
  'Health is not about the weight you lose, but the life you gain.',
  'One cannot think well, love well, sleep well, if one has not dined well. — Virginia Woolf',
  'Good nutrition creates health in all areas of our existence.',
  'Every time you eat is a chance to nourish your body.',
  'The doctor of the future will interest patients in the care of the human frame and in diet. — Thomas Edison',
  'Don’t eat anything your great-grandmother wouldn’t recognize as food. — Michael Pollan',
  'A fit body, a calm mind, a home full of love — these must be earned.',
  // ── Habits & consistency ──
  'Small changes every day add up to remarkable results.',
  'Progress, not perfection.',
  'Discipline is choosing between what you want now and what you want most.',
  'Motivation gets you started; habit keeps you going.',
  'You don’t have to be extreme, just consistent.',
  'Success is the sum of small efforts repeated day in and day out. — Robert Collier',
  'The secret of getting ahead is getting started. — Mark Twain',
  'A year from now you’ll wish you had started today.',
  'Take care of your body — it’s the only place you have to live. — Jim Rohn',
  'It’s not about having time. It’s about making time.',
  'The body achieves what the mind believes.',
  'Fall in love with taking care of yourself.',
  'Your future is created by what you do today, not tomorrow.',
  'Habits are the compound interest of self-improvement. — James Clear',
  'Do something today that your future self will thank you for.',
  'Little by little, a little becomes a lot.',
  'Consistency is more important than intensity.',
  'You didn’t come this far to only come this far.',
  'It’s the pattern that counts — not any single meal.',
  'Slow progress is still progress.',
  // ── Hydration, sleep, movement ──
  'Water is the driving force of all nature. — Leonardo da Vinci',
  'Drink water like it’s your job.',
  'Sleep is the best meditation. — Dalai Lama',
  'A good laugh and a long sleep are the two best cures for anything. — Irish Proverb',
  'Movement is medicine for the body, mind, and mood.',
  'Walking is the best possible exercise. — Thomas Jefferson',
  'An early-morning walk is a blessing for the whole day. — Henry David Thoreau',
  'Rest when you’re weary — refresh and renew yourself.',
  'Exercise changes your body, your attitude, and your mood.',
  'Take a deep breath. It’s just a bad day, not a bad life.',
  'Hydration is the foundation of energy.',
  'Your body was made to move — give it the chance.',
  'The only bad workout is the one that didn’t happen.',
  'Eight hours of sleep isn’t a luxury — it’s maintenance.',
  'Stretch your body, and your mind will follow.',
  'Every step counts, even the small ones.',
  'Rest is not idleness — it’s part of the work.',
  'Energy and persistence conquer all things. — Benjamin Franklin',
  'Move your body every day. Motion is life.',
  'Breathe. You’ve got this.',
  // ── Mindset & self-care ──
  'Self-care is not selfish. You cannot serve from an empty vessel. — Eleanor Brownn',
  'Almost everything will work again if you unplug it for a few minutes — including you. — Anne Lamott',
  'You can’t pour from an empty cup — take care of yourself first.',
  'Wellness is the complete integration of body, mind, and spirit. — Greg Anderson',
  'Make your happiness a priority — it isn’t selfish. — Mandy Hale',
  'Happiness is the highest form of health. — Dalai Lama',
  'Health is a state of harmony of body, mind, and spirit. — B.K.S. Iyengar',
  'Be gentle with yourself — you’re doing the best you can.',
  'Nourish your mind as carefully as you nourish your body.',
  'A calm mind brings inner strength and self-confidence. — Dalai Lama',
  'Take rest; a field that has rested gives a bountiful crop. — Ovid',
  'You are worth the effort it takes to care for yourself.',
  'Peace begins with a healthy body and a quiet mind.',
  'Don’t compare your chapter one to someone else’s chapter twenty.',
  'The groundwork of all happiness is health. — Leigh Hunt',
  'Your body hears everything your mind says — speak kindly.',
  'Feelings are just visitors. Let them come and go.',
  'Healing is a matter of time, but also of opportunity. — Hippocrates',
  'Caring for myself is not self-indulgence, it is self-preservation. — Audre Lorde',
  'A healthy mind lives in a healthy body.',
  // ── Coaching & encouragement ──
  'Every expert was once a beginner.',
  'You’re not starting over — you’re starting wiser.',
  'Celebrate every small win along the way.',
  'The best project you’ll ever work on is you.',
  'Believe you can and you’re halfway there. — Theodore Roosevelt',
  'Strive for progress, not perfection.',
  'One healthy choice leads to another.',
  'Your only limit is you — and you can move it.',
  'Great things never come from comfort zones.',
  'Trust the process; your body is listening.',
  'Change happens one plate, one step, one day at a time.',
  'Health is an investment, not an expense.',
  'The journey of a thousand miles begins with one step. — Lao Tzu',
  'You are stronger than your excuses.',
  'Feed your body. Fuel your goals.',
  'Eat well, move often, sleep deeply, stress less.',
  'Wellness is not a destination, it’s a way of traveling.',
  'The best time to plant a tree was 20 years ago. The second best time is now.',
  'Choose habits today that your body will thank you for tomorrow.',
  'Good health is a crown that only the sick can see.',

  // ══════════════ EXPANDED SET ══════════════

  // ── More food & mindful eating ──
  'Eat the rainbow — color on your plate means life in your cells.',
  'Cooking is love made visible.',
  'The kitchen is the heart of a healthy home.',
  'When diet is wrong, medicine is of no use. When diet is correct, medicine is of no need. — Ayurvedic Proverb',
  'Fill your plate with color and your body with life.',
  'Whole foods, whole health.',
  'Fresh, simple, and real beats packaged and processed.',
  'Skip the guilt, keep the greens.',
  'Portion your plate, not your joy.',
  'Slow down — digestion begins in the mind.',
  'Chew your food; your stomach has no teeth.',
  'A colorful plate is a healthy plate.',
  'Fuel first, indulge second.',
  'Real change starts on your fork.',
  'Eat mindfully; taste every bite.',
  'Your gut is your second brain — feed it well.',
  'Fiber today keeps sluggishness away.',
  'Protein builds you; patience shapes you.',
  'Greens on the plate, glow on the face.',
  'Cook more, worry less.',
  'The best diet is the one you can keep.',
  'Balance, not restriction.',
  'Nourish, don’t punish.',
  'Eat like you love yourself.',
  'Homemade beats takeaway, almost every time.',
  'Season with herbs, not regret.',
  'Mindful bites, mighty results.',
  'Feed the body you want, not the cravings you have.',
  'Every healthy meal is a promise kept to yourself.',
  'Let hunger guide you, not the clock.',
  'Good food is good mood.',
  'Add veggies before you subtract treats.',
  'Plan your plate, win your day.',
  'A full plate of vegetables never left anyone worse off.',
  'Water before coffee, greens before grains.',
  'Eat slowly; your body will tell you when it’s enough.',
  'The healthiest snack is the one you prepared yourself.',
  'Sugar is a guest, not a resident.',
  'Real hunger waits; cravings shout — learn the difference.',
  'Cook once, nourish twice — leftovers are a gift.',
  'A plant on your plate a day keeps the pharmacy away.',
  'Eat for the body you’re building, not the mood you’re in.',
  'Flavor comes from spices, not from excess.',
  'Fresh water, fresh start.',
  'Nutrition is not about being perfect; it’s about being consistent.',
  'The kitchen is your first pharmacy.',
  'You can’t out-train a poor diet.',
  'Every vegetable you add crowds out something you don’t need.',
  'Small plate, mindful pace, satisfied face.',
  'Respect your food and it will respect your body.',

  // ── Discipline, goals & consistency ──
  'Motivation is what gets you started. Habit is what keeps you going. — Jim Ryun',
  'We are what we repeatedly do. Excellence, then, is not an act but a habit. — Will Durant',
  'Discipline is the bridge between goals and accomplishment. — Jim Rohn',
  'Don’t wish it were easier; wish you were better. — Jim Rohn',
  'A goal without a plan is just a wish.',
  'Fall seven times, stand up eight. — Japanese Proverb',
  'The pain of discipline weighs ounces; the pain of regret weighs tons.',
  'Success isn’t always about greatness. It’s about consistency. — Dwayne Johnson',
  'You’ll never change your life until you change something you do daily.',
  'Discipline is remembering what you want.',
  'What you do every day matters more than what you do once in a while.',
  'The difference between who you are and who you want to be is what you do.',
  'Show up for yourself, especially on the hard days.',
  'You don’t need more time; you need more discipline.',
  'Winners are just ordinary people with extraordinary determination.',
  'Do the thing today that makes tomorrow easier.',
  'Direction is more important than speed.',
  'Little and often fills the purse.',
  'Habits made you; better habits will remake you.',
  'The secret to your future is hidden in your daily routine. — Mike Murdock',
  'Discipline equals freedom. — Jocko Willink',
  'Excuses burn calories of ambition, not of fat.',
  'One day or day one — you decide.',
  'Turn “I can’t” into “I will,” and “I wish” into “I did.”',
  'Set a goal so big that you can’t achieve it until you grow into it.',
  'Repetition is the mother of mastery.',
  'The body follows where the routine leads.',
  'Momentum builds from the smallest of starts.',
  'You are always one decision away from a healthier day.',
  'Aim for better, not perfect — and start now.',
  'Consistency compounds; skip a day, not a week.',
  'The plan works when you work the plan.',
  'Discipline today, freedom tomorrow.',
  'Great results demand small, boring, daily reps.',
  'Your habits are voting for the person you’re becoming.',
  'Dream big, start small, act now.',
  'Effort is a currency; spend it on yourself.',
  'The hardest step is the first one — take it today.',
  'Standards, not motivation, carry you on tired days.',
  'Focus on systems, and goals take care of themselves.',

  // ── Movement, fitness & energy ──
  'Those who think they have no time for exercise will sooner or later find time for illness. — Edward Stanley',
  'Take care of your body; it’s the engine that carries your dreams.',
  'A little progress each day adds up to a stronger you.',
  'Fitness is not about being better than someone else; it’s about being better than you used to be.',
  'Strength doesn’t come from what you can do; it comes from doing what you thought you couldn’t.',
  'Sweat is fat crying.',
  'The body will go almost anywhere the mind leads it.',
  'Motion creates emotion — move to lift your mood.',
  'A walk a day keeps the stiffness away.',
  'Train because you love your body, not because you hate it.',
  'Some days you won’t feel like it — do it anyway.',
  'Exercise is the most underused antidepressant.',
  'Your legs are not tired; your mind is.',
  'Push yourself, because no one else is going to do it for you.',
  'Fitness is a journey, not a destination.',
  'The clock is ticking. Are you becoming the person you want to be?',
  'Movement is a celebration of what your body can do.',
  'Every workout is progress, no matter how small.',
  'Start where you are. Use what you have. Do what you can. — Arthur Ashe',
  'Energy is contagious — create it by moving.',
  'A body in motion stays in motion.',
  'Get moving; momentum handles the rest.',
  'The gym is a therapy session you sweat through.',
  'Do it for the person you’re becoming.',
  'Stronger every day, in body and in mind.',
  'Movement first, mood follows.',
  'Rome wasn’t built in a day, and neither is a strong body.',
  'Walk it out — the body clears what the mind can’t.',
  'You don’t have to go fast; you just have to go.',
  'Ten minutes of movement beats zero, every time.',
  'Fitness is freedom in a body.',
  'Progress is built rep by rep, step by step.',
  'Feel the burn now, feel the pride later.',
  'Train the body, and the confidence follows.',
  'Consistency in the gym is confidence in life.',
  'Your future self is watching you right now through memories.',
  'Move a little more today than yesterday.',
  'Strong is the new goal, not skinny.',
  'The best exercise is the one you’ll actually do.',
  'Energy spent on health is never wasted.',

  // ── Hydration, sleep & rest ──
  'Thousands have lived without love, not one without water. — W. H. Auden',
  'Sleep is the golden chain that ties health and our bodies together. — Thomas Dekker',
  'A well-rested body is a resilient body.',
  'When you can’t control your mind, control your breath.',
  'Water is life’s matter and matrix, mother and medium. — Albert Szent-Györgyi',
  'Hydrate before you caffeinate.',
  'Good sleep is the cheapest medicine you’ll ever take.',
  'Rest is productive.',
  'Recovery is where the growth happens.',
  'Silence and sleep are the body’s quiet repair crew.',
  'Your body whispers before it screams — listen and rest.',
  'A glass of water can fix more than you think.',
  'Protect your sleep like you protect your goals.',
  'Downtime is not wasted time.',
  'Rest so you can rise.',
  'The night’s sleep decides the next day’s strength.',
  'Slow mornings build steady days.',
  'Stillness is where energy is rebuilt.',
  'Drink water, then decide you’re tired.',
  'Naps are not weakness; they’re maintenance.',
  'Give your body the rest it earned.',
  'Hydration is quiet self-respect.',
  'Sleep is the foundation the whole day is built on.',
  'A rested mind makes better food choices.',
  'When in doubt, drink water and take a walk.',
  'Rest your body; the goals will still be there tomorrow.',
  'Deep breaths are free medicine.',
  'Guard your evenings; they shape your mornings.',
  'Recover with intention, not guilt.',
  'Calm is a superpower — sleep is where it’s charged.',

  // ── Mindset, motivation & goals ──
  'Whether you think you can or you think you can’t, you’re right. — Henry Ford',
  'The only person you should try to be better than is the one you were yesterday.',
  'Doubt kills more dreams than failure ever will.',
  'You are capable of amazing things.',
  'Fall in love with the process and the results will come.',
  'Your body can stand almost anything. It’s your mind you have to convince.',
  'Difficult roads often lead to beautiful destinations.',
  'The comeback is always stronger than the setback.',
  'You didn’t wake up today to be mediocre.',
  'Dream it. Believe it. Build it.',
  'Great changes begin with a single decision.',
  'Focus on how far you’ve come, not how far you have to go.',
  'The struggle you’re in today builds the strength you need tomorrow.',
  'You are not behind; you are on your own path.',
  'A little bit better is still better.',
  'Turn your setbacks into comebacks.',
  'What you focus on grows.',
  'Your mind is a garden; your thoughts are the seeds.',
  'You get what you commit to, not what you wish for.',
  'The best view comes after the hardest climb.',
  'Persist. Nothing worthwhile comes easy.',
  'Change your thoughts and you change your world. — Norman Vincent Peale',
  'A goal is a dream with a deadline.',
  'You can’t go back and start over, but you can start now and finish strong.',
  'One step forward is still forward.',
  'Believe in the person you’re becoming.',
  'Your potential is a promise waiting to be kept.',
  'Discomfort is the price of admission to a better you.',
  'Small wins build big belief.',
  'Nothing changes if nothing changes.',
  'You are the author of your own health story.',
  'Focus on the next right choice, not the whole journey.',
  'Confidence comes from kept promises to yourself.',
  'Growth begins at the edge of your comfort zone.',
  'Winning starts with beginning.',
  'Your effort today is a gift to your future self.',
  'Keep going — the middle is always the messiest part.',
  'Be the reason you smile in the mirror.',
  'Progress lives just outside your excuses.',
  'You are one healthy habit away from a better week.',
  'Hope anchored in action becomes results.',
  'Do it scared, do it tired, but do it.',
  'The best time to begin again is right now.',
  'Fear is a liar; try it and see.',
  'Every champion was once a contender who refused to give up.',
  'Your only competition is the person you were yesterday.',
  'Make peace with slow — it still moves forward.',
  'Big journeys are just small steps stacked with patience.',
  'You have survived 100% of your worst days.',
  'Start before you feel ready.',

  // ── Self-care, self-compassion & mental wellness ──
  'Talk to yourself like someone you love. — Brené Brown',
  'Rest is not a reward for finishing; it’s part of the work.',
  'You are allowed to be both a masterpiece and a work in progress.',
  'Be kind to your mind.',
  'It’s okay to have a bad day; it isn’t okay to give up.',
  'Self-love is the foundation of every healthy habit.',
  'Slow down; you’re not a machine.',
  'Your worth is not measured by the scale.',
  'Progress, not pressure.',
  'Give yourself the grace you give others.',
  'A gentle approach lasts longer than a harsh one.',
  'You deserve the care you so freely give.',
  'Compassion for yourself is where healing begins.',
  'Your best is enough, even on the hard days.',
  'One kind thought can change your whole day.',
  'Take the pressure off; take the next small step.',
  'Healthy isn’t a look; it’s a feeling.',
  'You are more than a number, a size, or a streak.',
  'Rest without guilt; you’ve earned it.',
  'Choose peace over perfection.',
  'A quiet walk can settle a loud mind.',
  'Feelings pass; take care of yourself while they do.',
  'Self-care is how you take your power back. — Lalah Delia',
  'Breathe in calm, breathe out tension.',
  'You can restart your day at any moment.',
  'Being gentle with yourself is a strength, not a weakness.',
  'Fill your own cup first, then pour into others.',
  'Every day is a fresh chance to care for yourself.',
  'Health includes the mind, not just the body.',
  'You don’t have to earn rest.',
  'Speak life over yourself.',
  'Let today be enough.',
  'Peace is a daily practice, not a destination.',
  'Your journey is yours — no need to rush it.',
  'A calm body starts with a calm breath.',
  'You are worthy of care exactly as you are.',
  'Grace over guilt, always.',
  'Kindness toward yourself is contagious to others.',
  'Take up space; you belong here.',
  'Small acts of self-care are big acts of self-respect.',

  // ── Health as wealth, prevention & longevity ──
  'Prevention is better than cure. — Desiderius Erasmus',
  'It is health that is real wealth, and not pieces of gold and silver. — Mahatma Gandhi',
  'A healthy body is a guest chamber for the soul; a sick body is a prison. — Francis Bacon',
  'Early to bed and early to rise makes a man healthy, wealthy, and wise. — Benjamin Franklin',
  'Look after your body — it has to last a lifetime.',
  'Invest in your health before you have to spend on illness.',
  'The best doctor gives the least medicine. — Benjamin Franklin',
  'Wellness today is freedom tomorrow.',
  'You only get one body — maintain it like it matters.',
  'Small daily habits are the compound interest of a long life.',
  'Care for your body now, thank yourself later.',
  'Health is the greatest gift, contentment the greatest wealth. — Buddha',
  'The groundwork for all longevity is laid in daily choices.',
  'Age is a number; vitality is a habit.',
  'Take medicine as a last resort, and food as a first.',
  'A stitch in time saves nine — and a walk today saves a decade.',
  'Longevity is built one healthy day at a time.',
  'Guard your health as your greatest asset.',
  'The habits you build today write the story of your later years.',
  'What we do now echoes in our health for years. (adapted)',
  'Strong foundations today, steady health tomorrow.',
  'A healthy lifestyle is the best insurance policy.',
  'Small deposits of wellness pay lifelong dividends.',
  'Move today so you can move at ninety.',
  'Prevention is the quietest kind of courage.',
  'Feed the future you with the choices of today.',
  'Health compounds — start the account early.',
  'The best time to protect your health was yesterday; the next best is now.',
  'A little care each day keeps big trouble away.',
  'Your habits are your health’s savings account.',

  // ── Nutritionist / coach perspective ──
  'Care for the person, not just the plate.',
  'Every client is a story in progress.',
  'Meet people where they are, then walk with them forward.',
  'Small, sustainable steps change lives.',
  'Behind every plan is a person worth believing in.',
  'You can’t change a habit you shame; you change the one you support.',
  'Progress in a client is progress in the world.',
  'Coach the mindset, and the meals follow.',
  'Empower, don’t restrict.',
  'A good plan is one a person can actually live.',
  'Habits, not crash diets, build lasting health.',
  'Listen first; advise second.',
  'The best plan is the one they’ll follow.',
  'Guide gently; results grow in patient soil.',
  'Celebrate the client’s wins louder than your own.',
  'Nutrition is personal — so is the way you teach it.',
  'Teach people to fish, and they eat well for a lifetime.',
  'Compassion is a clinical skill.',
  'Data informs; empathy transforms.',
  'Consistency from a client beats perfection any day.',
  'Every small victory deserves acknowledgment.',
  'Sustainable beats spectacular.',
  'Health is built on trust between coach and client.',
  'Help people eat well and feel better.',
  'Healthy habits, built one day at a time.',
  'Change happens at the speed of trust.',
  'Progress is personal; honor each person’s pace.',
  'A kind word can restart a stalled journey.',
  'Behavior change is a marathon coached mile by mile.',
  'The goal isn’t a diet; it’s a lifestyle they own.',

  // ── Balance, moderation & sustainability ──
  'Everything in moderation, including moderation. — Oscar Wilde',
  'Balance is not something you find; it’s something you create.',
  'One indulgence won’t break you; consistency will make you.',
  'The 80/20 rule: eat well most of the time, live a little the rest.',
  'A sustainable plan beats a perfect one you can’t keep.',
  'You can enjoy the treat and honor the goal.',
  'Flexibility is the secret ingredient of lasting change.',
  'Restriction breeds rebellion; balance builds freedom.',
  'A healthy life leaves room for cake on birthdays.',
  'Aim for better, not perfect.',
  'Guilt is not a nutrient — leave it off the plate.',
  'The best routine bends without breaking.',
  'Enjoy your food; just choose most of it well.',
  'Moderation today keeps extremes away.',
  'Health is a lifestyle, not a punishment.',
  'You don’t fail by having a treat; you fail by giving up.',
  'Balance means the scale of your life, not just the scale in your bath.',
  'Sustainable habits outlive strict rules.',
  'Progress loves patience and hates all-or-nothing.',
  'A flexible plan is a plan that survives real life.',

  // ── Gratitude, joy & purpose ──
  'Gratitude turns what we have into enough.',
  'A grateful heart is a magnet for wellness.',
  'Health is the ability to fully enjoy life.',
  'Joy is the best medicine you can serve daily.',
  'Find something to be thankful for at every meal.',
  'A cheerful heart is good medicine. — Proverbs 17:22',
  'Live so that your body can keep up with your dreams.',
  'Purpose is the vitamin that motivation runs on.',
  'Do what makes your soul and your body thrive.',
  'Laughter is a full-body reset.',
  'Count your blessings, then take a walk to enjoy them.',
  'Wellness is remembering to be present.',
  'Health lets you say yes to the life you love.',
  'Feed your joy as carefully as you feed your body.',
  'A grateful mind is a healthy mind.',
  'Move with joy, not obligation.',
  'The reward for good habits is a life you enjoy living.',
  'Peace, plate, and purpose — a healthy trio.',
  'Savor the journey, not just the results.',
  'A thankful spirit lightens every burden.',

  // ── Short, punchy reminders ──
  'Drink water.',
  'Eat your greens.',
  'Take the stairs.',
  'Move a little.',
  'Rest well tonight.',
  'One bite at a time.',
  'You’ve got today.',
  'Start small; start now.',
  'Keep it simple.',
  'Show up anyway.',
  'Better than yesterday.',
  'Breathe and begin.',
  'Fuel, don’t fill.',
  'Progress over pressure.',
  'Choose you today.',
  'Slow bites, big wins.',
  'Stand up, stretch, smile.',
  'Small steps, steady wins.',
  'Nourish, move, rest, repeat.',
  'Today counts.',
  'Hydrate and elevate.',
  'Consistency wins.',
  'Health first.',
  'One good choice, then another.',
  'You’re doing better than you think.',
  'Kindness in, calm out.',
  'Plate it colorful.',
  'Rest is fuel too.',
  'Keep the streak alive.',
  'Little wins matter.',

  // ── More nutrition science & habits ──
  'Protein at every meal keeps hunger honest.',
  'Front-load your day with vegetables.',
  'The best salad dressing is one you can pronounce.',
  'Cook in batches; decisions get easier.',
  'A stocked fridge is a healthy fridge.',
  'Read the label; know your food.',
  'Fiber is the unsung hero of a healthy gut.',
  'Colorful vegetables carry the vitamins pills only imitate.',
  'Prep on Sunday; thank yourself all week.',
  'Trade the drive-through for the cutting board.',
  'Whole grains, whole energy.',
  'A handful of nuts beats a bag of chips.',
  'Drink your water before your soda.',
  'Healthy swaps beat harsh bans.',
  'The plate method: half veggies, quarter protein, quarter grains.',
  'Snack with purpose, not on autopilot.',
  'Fresh fruit is nature’s fast food.',
  'Slow-cooked patience makes tender health.',
  'Spice it up; flavor need not cost your goals.',
  'Eat close to the earth, feel close to your best.',
  'Good habits taste better with time.',
  'Fewer ingredients, more nourishment.',
  'Plan the week; free the mind.',
  'A green smoothie is a salad you can sip.',
  'Meal prep is self-care you can eat.',
  'Choose water first and often.',
  'Herbs and spices heal what salt only hides.',
  'Home cooking is the original wellness hack.',
  'Fill up on plants; the rest falls into place.',
  'Eat until satisfied, not until stuffed.',

  // ── Resilience & perseverance ──
  'Rock bottom became the solid foundation on which I rebuilt my life. — J.K. Rowling',
  'It always seems impossible until it’s done. — Nelson Mandela',
  'Our greatest glory is not in never falling, but in rising every time we fall. — Confucius',
  'Perseverance is not a long race; it’s many short races one after another.',
  'Tough times never last, but tough people do. — Robert Schuller',
  'The struggle is part of the story.',
  'When you feel like quitting, remember why you started.',
  'Storms make trees take deeper roots.',
  'You are braver than you believe, stronger than you seem.',
  'Every setback is a setup for a comeback.',
  'Keep swimming when the water gets deep.',
  'Strength grows in the moments you think you can’t go on but keep going anyway.',
  'A river cuts through rock not by power but by persistence.',
  'Don’t stop when you’re tired; stop when you’re done.',
  'Resilience is built one hard day at a time.',
  'The wound is the place where the light enters you. — Rumi',
  'You can begin again as many times as you need.',
  'Falling down is part of learning to fly.',
  'Endurance is the quiet cousin of victory.',
  'The comeback is stronger than the setback — always.',
  'Grow through what you go through.',
  'Patience and persistence perform miracles.',
  'Some days you plant; some days you harvest — keep tending.',
  'A slow recovery is still a recovery.',
  'Fall in love with beginning again.',
  'The bamboo bends but does not break.',
  'Progress is quiet; keep going even when no one claps.',
  'Every mile you cover changes you.',
  'The seed doesn’t see the flower — it just keeps growing.',
  'Stay the course; the tide always turns.',

  // ── Closing encouragements ──
  'You are exactly where you need to be to begin.',
  'Health is a daily choice, and today you get to choose.',
  'Take the next small step; the path reveals itself.',
  'Your effort matters, even when the scale is quiet.',
  'A better you is built in ordinary moments.',
  'Wellness is a thousand small kindnesses to yourself.',
  'Keep showing up — future you is counting on it.',
  'The best investment you’ll ever make is in your own health.',
  'One day at a time, one choice at a time, you’re getting there.',
  'You have everything you need to start today.',
];

/**
 * Deterministic quote for the given day (defaults to today). Because it keys off
 * the calendar day, every client and nutritionist sees the same quote each day,
 * and it advances once per day, cycling through the whole set over time.
 */
export function quoteOfTheDay(date: Date = new Date()): string {
  const dayIndex = Math.floor(date.getTime() / 86_400_000);
  const len = WELLNESS_QUOTES.length;
  return WELLNESS_QUOTES[((dayIndex % len) + len) % len];
}
